package live.agor.app.automation

object AutomationProtocol {
    const val ACTION_CONTROL = "live.agor.app.action.AGOR_CONTROL"
    const val EXTRA_COMMAND_JSON = "live.agor.app.extra.CONTROL_COMMAND_JSON"
    const val EXTRA_COMMAND_JSON_BASE64 = "live.agor.app.extra.CONTROL_COMMAND_JSON_BASE64"
    const val EXTRA_RESPONSE_ACTION = "live.agor.app.extra.CONTROL_RESPONSE_ACTION"
    const val EXTRA_RESPONSE_REQUEST_ID = "live.agor.app.extra.CONTROL_RESPONSE_REQUEST_ID"
    const val EXTRA_COMMAND = "live.agor.app.extra.COMMAND"
    const val EXTRA_REQUEST_ID = "live.agor.app.extra.REQUEST_ID"
    const val EXTRA_SERVER_URL_LEGACY = "live.agor.app.extra.SERVER_URL"
    const val EXTRA_EMAIL_LEGACY = "live.agor.app.extra.EMAIL"
    const val EXTRA_PASSWORD_LEGACY = "live.agor.app.extra.PASSWORD"
    const val EXTRA_API_KEY_LEGACY = "live.agor.app.extra.API_KEY"
    const val EXTRA_CONNECT_SOCKET_LEGACY = "live.agor.app.extra.CONNECT_SOCKET"

    const val KEY_COMMAND = "command"
    const val KEY_REQUEST_ID = "requestId"
    const val KEY_SUCCESS = "success"
    const val KEY_MESSAGE = "message"

    const val KEY_SERVER_URL = "serverUrl"
    const val KEY_EMAIL = "email"
    const val KEY_PASSWORD = "password"
    const val KEY_API_KEY = "apiKey"
    const val KEY_CONNECT_SOCKET = "connectSocket"

    const val KEY_HERMES_WEBHOOK = "hermesWebhook"
    const val KEY_HERMES_PROMPT = "hermesPrompt"
    const val KEY_HERMES_URL = "hermesUrl"
    const val KEY_HERMES_TOKEN = "hermesToken"
    const val KEY_HERMES_MODEL = "hermesModel"
    const val KEY_PROMPT = "prompt"
    const val KEY_WEBHOOK = "webhook"
    const val KEY_SESSION_ID = "sessionId"
    const val KEY_WAIT_FOR_COMPLETION = "waitForCompletion"
    const val KEY_TIMEOUT_MS = "timeoutMs"
    const val KEY_IMAGES = "images"
    const val KEY_DATA_URL = "dataUrl"

    const val COMMAND_LOGIN = "login"
    const val COMMAND_HERMES_CONFIGURE = "hermes.configure"
    const val COMMAND_HERMES_CHAT = "hermes.chat"
    const val COMMAND_HERMES_TRIGGER = "hermes.trigger"
    const val COMMAND_HERMES_CAPABILITIES = "hermes_capabilities"
    const val COMMAND_HERMES_SESSION_CREATE = "hermes_session_create"
    const val COMMAND_HERMES_SESSION_LIST = "hermes_session_list"
    const val COMMAND_HERMES_SESSION_DELETE = "hermes_session_delete"
    const val COMMAND_HERMES_SEND = "hermes_send"
    const val COMMAND_HERMES_STATUS = "hermes_status"
    const val COMMAND_HERMES_CANCEL = "hermes_cancel"
    const val COMMAND_HERMES_LAST_RESPONSE = "hermes_last_response"
    const val COMMAND_PING = "ping"
}
